apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "[[service]].name" . }}
  labels:
    app: {{ template "[[service]].name" . }}
    chart: {{ template "[[service]].chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "[[service]].name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "[[service]].name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: "{{ .Values.images.main }}"
{{- if eq .Values.env "prod" }}
          imagePullPolicy: IfNotPresent
{{- else }}
          imagePullPolicy: Always
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livelinessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
